### ISSUE TITLE
"Segmentation fault: 11" when generating a graphic

### ISSUE THREAD

**Issue by edgingtonn1** [widdowquinn/pyani#1]
Hi,
Thanks for creating pyani. When trying to generate graphics of any sort, I get a "Segmentation fault: 11" error.  I am using the Continuum Anaconda distribution of python2.7, and I have all of the dependencies installed.  The error occurred with your test files, as well as with my own fasta files. The graphic format type did not matter. 
```
$ ./average_nucleotide_identity.py -i tests/test_ani_data/ -o tests/test_ANIm_output -m ANIm -g
Segmentation fault: 11
```
If you need more system details, let me know. I am new to posting issues.
Best,
-Nicholas

**Comment by widdowquinn** [comment]
Hi Nicholas,

Thanks for raising the issue - my first suspicion is that there's a configuration problem. Would you be able to provide more information about your OS (including version), and also provide the logfile output from a failing test run? You should be able to get this with the -v or -l <LOGFILE> options at the command-line. That should help determine whether/where the problem is in pyani.

Many thanks,

L.

**Comment by edgingtonn1** [comment]
Hi Leighton,
I figured it out. My installation of MUMmer was the problem. After reinstalling it, everything has been great. Thanks for the quick response. This is an excellent and well written script.
Best,
-N.
