### ISSUE TITLE
Execution Error

### ISSUE THREAD

**Issue by aupadrasta** [widdowquinn/pyani#107]
#### Summary:
After installation of pyani using pip3 
ran the following command from the root 
average_nucleotide_identity.py -h

#### Description:
No module named pyani
Module not found

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.

#### Current Output:
average_nucleotide_identity.py -h
Traceback (most recent call last):
  File "/home/aditya/.local/bin/average_nucleotide_identity.py", line 169, in <module>
    from pyani import (anib, anim, tetra, pyani_config, pyani_files,
ModuleNotFoundError: No module named 'pyani'

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

**Comment by widdowquinn** [comment]
Hi aupadrasta,

The issue here is that `average_nucleotide_identity.py` should not be run from the source directory.

After installing `pyani` with `pip3 install pyani` (for which you don't need to download the source), the script `average_nucleotide_identity.py` should be available in your `${PATH}`, just as any other installed package.

If you try to run `average_nucleotide_identity.py` from the source directory, Python gets confused about where it should be importing the `pyani` module from, and gives you the error you see.

Please try changing to your home directory, then running `average_nucleotide_identity.py -h` from the command-line, and seeing if you get the help/usage information. If you do, then `pyani` is installed as expected. If you still see an error, please do report it here.

Cheers,

L.

**Comment by aupadrasta** [comment]
I wasn't able to get it work. I changed to home directory but still its the same
Second option: I downloaded the Pyani master package and unziped and tried to run the script from there but its showing the same.
May be something really basic stuff in Linux am missing out

**Comment by widdowquinn** [comment]
Hmm… that's disappointing.

Can you please try to import the `pyani` package into Python, to confirm that it's installed and available to the script? If you've not done this before, the way to do it is this:

```
~$ python
Python 3.6.3 (default, Oct  4 2017, 06:09:38) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyani
>>> 
```

If `pyani` is not available, you should see something like this:

```
~$ python3
Python 3.6.3 (default, Oct  4 2017, 06:09:38) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyani
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pyani'
>>> 
```

If that's the case, then there is likely some complexity in your Python installation. It's possible to have more than one version of Python installed on your machine (as I do - seen in the examples above), and when you install `pyani` under one of them, it's not visible to the others. It should be the case that the `average_nucleotide_identity.py` script points to the version of Python it's installed under - that doesn't seem to be happening for you, and there are several possible reasons for that. Would you be able to provide a step-by-step account of how you download and install `pyani` to help solve the problem?

**Comment by widdowquinn** [comment]
One thing that may be useful is to report the result of issuing the commands:

```
$ which python
$ which python3
```
(this will tell us where your default Python installation is/are)

and 

```
head /home/aditya/.local/bin/average_nucleotide_identity.py
```

(this will tell us where `average_nucleotide_identity.py` is expecting to find Python)

**Comment by aupadrasta** [comment]
Please find the attached with the steps I followed for installation
[Steps_used_pyani_installation.docx](https://github.com/widdowquinn/pyani/files/1708292/Steps_used_pyani_installation.docx)

**Comment by widdowquinn** [comment]
Thanks for that - it's very helpful!

I can see three informative things, here:

1. Your default Python is the one provided by miniconda.
2. Using `pip` did not install `pyani` in the miniconda version of Python. As `pip` is installed as part of miniconda, that's a little confusing, but it may be due to your `${PATH}` prioritising the system version of `pip`.
3. There's a typo in your `head …` command - the `aditya` directory is missing - so we're lacking information about which Python version the `average_nucleotide_identity.py` program is looking at. My guess would be that it is not the one you get from typing `which python3`…

It does suggest three possible solutions, though - if you're willing to try them.

1) Use the conda package

Someone (not me) has very kindly turned the most recent release of `pyani` into a conda package. This should work with your miniconda installation directly:

```bash
conda install pyani
```

* <https://anaconda.org/bioconda/pyani>

Please try this and let me know if it works for you.

2) Use the `pip` module installation approach.

Rather than using the `pip` command (which might not be the one for your version of Python), you can use the `pip` *module*. It's very similar as a command:

```bash
$ python3 -m pip install -r requirements.txt
$ python3 -m pip install pyani
```
That *should* force installation into your miniconda Python. If the conda package fails, please give it a try and let me know how that works.

3) Use the `setup.py` file

From the root of the `pyani` repository, you should be able to issue the command:

```bash
python3 setup.py install
```

and have the `setup.py` grab the necessary requirements, as well as install `pyani`.

If the other two methods fail, please try this, and let me know how you get on.
