### ISSUE TITLE
Genbank get genomes by taxon .py error

### ISSUE THREAD

**Issue by stevebaeyen** [widdowquinn/pyani#108]
#### Summary:
TypeError while downloading with genbank_get_genomes.py script from cloned repo for taxid 294

#### Description:
I got this error with a newly installed pyani. Downloaded the repo from git and used the script from there, but I get the same error: int() argument must be a string, not 'NoneType' on the download of GCF_000801915.1. I also did not get a classes and labels file in the output

#### Reproducible Steps:
command used: genbank_get_genomes_by_taxon.py -o genomes -v -t 294 -l pf_downloads.log --email steve.baeyen@ilvo.vlaanderen.be

#### Current Output:
Scripts stops after 103 genomes, no classes and labels files.

#### Expected Output:
All genomes from taxid and labels + classes file.

**Comment by widdowquinn** [comment]
Just a wee note to say I've seen this and I'm not ignoring it - just a bit busy and I'll get to it shortly. Many apologies for the delay.

**Comment by widdowquinn** [comment]
Hi Steve,

I've just tried your command with the current `HEAD` from this repository, and it worked for me.

```bash
$ genbank_get_genomes_by_taxon.py -o genomes -v -t 294 -l pf_downloads.log --email steve.baeyen@ilvo.vlaanderen.be
[…]
INFO: Skipped assembly UIDs: ['654118', '490488', '426538', '381388', '381368', '380888']
INFO: Sun Feb 25 16:55:15 2018
INFO: Done.
```

- [pf_downloads.log](https://github.com/widdowquinn/pyani/files/1756485/pf_downloads.log)

I can't tell what would be wrong from this. Did you happen to preserve your own `pf_downloads.log` file? It might have recorded the stack trace, and help me spot where the problem was.

I have a suspicion that NCBI returned an error message that the program made a brave attempt at parsing, but ultimately failed. Unless I can provoke the same error, I'll have to rely on your logfile.

Did you retry the download command, by the way? It might work the second time if this is an intermittent error from NCBI's end.

L.

**Comment by stevebaeyen** [comment]
Hi Leighton,
I retried the command but I get the same error....I have attached the log file.
[pf_downloads.log](https://github.com/widdowquinn/pyani/files/1758082/pf_downloads.log)
regards,
Steve

**Comment by widdowquinn** [comment]
Hmm… unfortunately the logfile didn't capture the stack trace. Do you still have a copy of the precise error message/trace that reported the `int()`/`NoneType` error? That might help me track this down.

**Comment by widdowquinn** [comment]
I've just tried the command on a second machine and, again, the download worked without issue. You're using the repo from GitHub, but can we confirm that you're on the `master` branch, and at `commit 5528842`?

If you're on an earlier commit, please could you issue a `git pull` from inside the repo and reinstall? If you're not on the `master` branch, then please could you issue a `git checkout master`, make sure you're on the same commit, and then reinstall? If you're on the same commit, then I'm puzzled and I'll need the stacktrace for the error message to follow up.

If you like, you could try the new interface:

```bash
git checkout classify
pyani download -t 294 --email steve.baeyen@ilvo.vlaanderen.be -v -l pf_classify_download.log classify_genomes
```

The new interface also works for me.

**Comment by stevebaeyen** [comment]
Hi Leighton,
Is there already a new version with the modified code to install using pip3?
Have a nice weekend !
Steve

Steve Baeyen
Hoofddeskundige  |  Lab Manager
ILVO
Instituut voor Landbouw-, Visserij- en Voedingsonderzoek
Flanders Research Institute for Agriculture, Fisheries and Food
Eenheid Plant – Gewasbescherming / Plant Sciences Unit – Crop Protection
Burg. Van Gansberghelaan 96
9820 Merelbeke (Belgium)
T  +32 9 272 24 70
steve.baeyen@ilvo.vlaanderen.be<mailto:steve.baeyen@ilvo.vlaanderen.be>
www.ilvo.vlaanderen.be<http://www.ilvo.vlaanderen.be/>
[orcid_16x16] orcid.org/0000-0002-7192-2403<http://orcid.org/0000-0002-7192-2403>
[http://intranet.ilvo/Portals/0/images/Communicatie/Huisstijl/Twitter.jpg]<https://twitter.com/ILVOvlaanderen> [http://intranet.ilvo/Portals/0/images/Communicatie/Huisstijl/FB.jpg?ver=2016-07-04-151729-847] <http://www.facebook.com/instituutvoorlandbouwenvisserijonderzoek>  [http://intranet.ilvo/Portals/0/images/Communicatie/Huisstijl/LinkedIn.jpg] <https://www.linkedin.com/company/ilvo>
//////////////////////////////////////////////
[http://intranet.ilvo/Portals/0/images/Communicatie/Huisstijl/Leeuw.jpg]
Blijf op de hoogte van alle ILVO-nieuws,
Schrijf u vandaag nog in op onze nieuwsbrief<http://mailing.ilvo.vlaanderen.be/mailcamp/admin/index.php?Page=Forms&Action=View&id=1>

**Comment by widdowquinn** [comment]
Not on PyPI yet, I'm afraid.

You should be OK with the current `HEAD` of the `classify` branch, though.

**Comment by widdowquinn** [comment]
Hi bv!

Thanks for your interest in `pyani`. You're right - this should really be a new issue (click on `New Issue` at the top of this page).

The problem is likely to be that you haven't installed `BLAST` locally, have the wrong `BLAST`, or have installed `BLAST` in an unusual place. Alternatively, you might be trying to compare two or more genomes that are too distantly related to give a result. To determine which this is, I would need to look at a minimal failing dataset and your log file.

If you create a new issue, you'll see that the field to enter your issue has a template with questions that it would be helpful for you to answer. That might also set you on your way to solving the problem.

L.
