### ISSUE TITLE
all ANI values as 1.0

### ISSUE THREAD

**Issue by bv2810** [widdowquinn/pyani#110]
#### Summary:
Please provide a short summary (a couple of sentences).
Hi, I'm fairly new to bio informatics and I tried running average_nucleotide_identity.py form pyani to compare a set of genomes. On one computer it works fine but on the other it doesn't.

#### Description:
Describe the issue as clearly as possible.
When running average_nucleotide_identity.py using ANIb at the end it shows "at least one BLAST run has failed, ANIb might fail". When checking the output identity file all identity values equal 1.0

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.
I used this script:
~/Bin/ANI/average_nucleotide_identity.py \
  -i path to the input directory with the fasta files \
  -o path to the output directory \
  -m ANIb \
  -v 
If you have a reproducible example, please include it.

#### Current Output:
The current output. Knowing what is the current behavior is useful.
at the end it displays "at least one BLAST run failed, ANIb might fail". When I check the output identity file it says all sequences have an identity of 1.0

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

#### pyani Version:
latest
#### Operating System:
Ubuntu

**Comment by widdowquinn** [comment]
Hi - apologies for the delay. I'm on holiday and didn't see this issue raised.

In this case I think the error is informative: at least one of your BLAST runs failed, and the `average_nucleotide_identity.py` script then wrote a default output of all `1.0` values in the matrix as you describe.

Your next step should be to identify which BLAST run(s) failed, and determine why. The likely cause is that an empty BLAST output file was written because two genomes being compared were too distantly related for BLAST to find any similarities.

L.
