### ISSUE TITLE
AttributeError: 'str' object has no attribute 'exists'

### ISSUE THREAD

**Issue by pavlo888** [widdowquinn/pyani#181]
#### Summary:
Please provide a short summary of your issue (in a couple of sentences).
I am trying to run the following command `average_nucleotide_identity.py -v -i fna/ -o test_ani -g --gformat png,pdf,eps --classes test_ani/classes.tab --labels test_ani/labels.tab` and I am getting the following error:

`INFO: Input directory: fna/
Traceback (most recent call last):
  File "/usr/local/bin/average_nucleotide_identity.py", line 11, in <module>
    load_entry_point('pyani==0.3.0a0', 'console_scripts', 'average_nucleotide_identity.py')()
  File "/usr/local/lib/python3.7/site-packages/pyani-0.3.0a0-py3.7.egg/pyani/scripts/average_nucleotide_identity.py", line 956, in run_main
  File "/usr/local/lib/python3.7/site-packages/pyani-0.3.0a0-py3.7.egg/pyani/scripts/average_nucleotide_identity.py", line 867, in build_logger
  File "/usr/local/lib/python3.7/site-packages/pyani-0.3.0a0-py3.7.egg/pyani/scripts/average_nucleotide_identity.py", line 440, in make_outdirs
AttributeError: 'str' object has no attribute 'exists'`

I am actually expecting to obtain an ANIb output. 

The pyani version I am using is pyani version: 0.3.0-alpha and I am currently in a macOS environment. 

These are the dependencies I have: 
`System information
	Platorm==Darwin-19.3.0-x86_64-i386-64bit
	Python==3.7.5 (default, Nov  1 2019, 02:16:23) 
[Clang 11.0.0 (clang-1100.0.33.8)]
Installed pyani Python dependendencies...
	Pillow==6.2.1 (/usr/local/lib/python3.7/site-packages)
	biopython==1.76 (/usr/local/lib/python3.7/site-packages)
	matplotlib==3.1.0 (/usr/local/lib/python3.7/site-packages)
	namedlist==1.7 (/usr/local/lib/python3.7/site-packages)
	networkx==2.4 (/usr/local/lib/python3.7/site-packages)
	numpy==1.18.2 (/usr/local/lib/python3.7/site-packages)
	openpyxl==3.0.3 (/usr/local/lib/python3.7/site-packages)
	pandas==1.0.3 (/usr/local/lib/python3.7/site-packages)
	scipy==1.4.1 (/usr/local/lib/python3.7/site-packages)
	seaborn==0.10.0 (/usr/local/lib/python3.7/site-packages)
	sqlalchemy==1.3.10 (/usr/local/lib/python3.7/site-packages)
	tqdm==4.43.0 (/usr/local/lib/python3.7/site-packages)
Installed pyani development dependendencies...
	bandit==Not Installed (-)
	black==Not Installed (-)
	codecov==Not Installed (-)
	coverage==Not Installed (-)
	doc8==Not Installed (-)
	flake8==Not Installed (-)
	jinja2==2.11.1 (/usr/local/lib/python3.7/site-packages)
	mypy==Not Installed (-)
	pydocstyle==Not Installed (-)
	pylint==Not Installed (-)
	pytest==5.4.1 (/usr/local/lib/python3.7/site-packages)
	pytest-cov==Not Installed (-)
	sphinx==2.4.4 (/usr/local/lib/python3.7/site-packages)
Installed pyani pip-install dependendencies...
	pre-commit==2.2.0 (/usr/local/lib/python3.7/site-packages)
	pytest-ordering==0.6 (/usr/local/lib/python3.7/site-packages)
	sphinx-rtd-theme==0.4.3 (/usr/local/lib/python3.7/site-packages)
Installed third-party tool versions...
Traceback (most recent call last):
  File "/usr/local/bin/pyani", line 11, in <module>
    load_entry_point('pyani==0.3.0a0', 'console_scripts', 'pyani')()
  File "/usr/local/lib/python3.7/site-packages/pyani-0.3.0a0-py3.7.egg/pyani/scripts/pyani_script.py", line 77, in run_main
  File "/usr/local/lib/python3.7/site-packages/pyani-0.3.0a0-py3.7.egg/pyani/scripts/subcommands/subcmd_listdeps.py", line 83, in subcmd_listdeps
  File "/usr/local/lib/python3.7/site-packages/pyani-0.3.0a0-py3.7.egg/pyani/dependencies.py", line 117, in get_tool_versions
  File "/usr/local/lib/python3.7/site-packages/pyani-0.3.0a0-py3.7.egg/pyani/anib.py", line 124, in get_version
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: PosixPath('blastn'): PosixPath('blastn')`

Could you help me solve this issue?

**Comment by widdowquinn** [comment]
Thanks for the bug report - much appreciated! I'll try to reproduce, then get back to you.

In the meantime, would you be able to share a small dataset that reproduces this error?

**Comment by pavlo888** [comment]
This is a set of 10 genomes. Hope it is enough.
 GCF_000016265.fna
<https://drive.google.com/file/d/1jA-xQcqZZzpvI_n9ljzlqxkmnzDHysfw/view?usp=drive_web>
 GCF_000016285.fna
<https://drive.google.com/file/d/1FZ29wz9OpqBM9_7uaKn8WmRonJnD5wAh/view?usp=drive_web>
 GCF_000020265.fna
<https://drive.google.com/file/d/1fJeWU3j_mu-SWOAtuVRfAyD-nPHvzDa-/view?usp=drive_web>
 GCF_000021345.fna
<https://drive.google.com/file/d/1LM_k3TUbgpF2EWk-hosxcaHyN9ErNdcD/view?usp=drive_web>
 GCF_000023185.fna
<https://drive.google.com/file/d/13WkQ-vctE76qpq-RpsRgNHe5trTXLWaB/view?usp=drive_web>
 GCF_000092025.fna
<https://drive.google.com/file/d/1rsePN8EsYddNl1amnIU8_KtcIzZTIuVQ/view?usp=drive_web>
 GCF_000092045.fna
<https://drive.google.com/file/d/18XCk7NglSGJEE5hIxH_TZgIbPXUlskYH/view?usp=drive_web>
 GCF_000192635.fna
<https://drive.google.com/file/d/1lqDvs1P5o8k42ohnTHWO5-adEAW1MvtB/view?usp=drive_web>
 GCF_000194195.fna
<https://drive.google.com/file/d/1lj0-KRODmpOpZaju2VOMj4bTjQ4RAPzp/view?usp=drive_web>
 GCF_000214615.fna
<https://drive.google.com/file/d/1qAd1zsZV4S7F39Lv8yFYfk-kp0CNBtVO/view?usp=drive_web>

**Comment by widdowquinn** [comment]
HI @pavlo888,

Apologies for the delay! That should be the `average_nucleotide_identity.py` script working (for ANIm, at least), with PR #182. Please can you check it works for you (I'll close this issue when you confirm). Also please read the last paragraph below - there's a new CLI for v0.3+.

I tracked down the initial issue, which was that when I moved this code over to using Python's `pathlib.Path` instead of strings for file paths, I didn't catch all instances where I was adding strings to them. This was throwing the error you see.

It also unearthed a few other errors, which I wasn't expecting, so much. Nearly all of these originated in problems with the `average_nucleotide_identity.py` script. It's not in the roadmap, but I intend to deprecate this script/way of running `pyani` eventually, but I want to leave it in place for a while to allow people to switch to the new interface. I haven't got round to doing all of that yet, so we shouldn't be surprised that some things aren't working, yet.

I really want to encourage everyone using v0.3+ to adopt the new approach described here: [https://pyani.readthedocs.io/en/latest/quickstart.html](https://pyani.readthedocs.io/en/latest/quickstart.html). This is the code that's being tested on this branch, and is working with ANIm.

Cheers,

L.

**Comment by pavlo888** [comment]
Hi Leighton,

So I tried installing pyani with conda but it does not seem to work. When I
run the command "pyani -h" it gives the following error:

(pyani) sam@bioinf-pc:~/Downloads/pyani_test$ pyani -h
pyani: command not found

I am currently working with python3

(pyani) sam@bioinf-pc:~/Downloads/pyani_test$ python3 --version
Python 3.8.2

So I am not sure what is wrong.

When I try the script you suggest, it does not work. It shows the following
error:

Traceback (most recent call last):
  File
"/home/sam/Downloads/pyani-master/pyani/scripts/average_nucleotide_identity.py",
line 156, in <module>
    from pyani.scripts import logger as pyani_logger
ModuleNotFoundError: No module named 'pyani.scripts'

Cheers,
Pablo

**Comment by widdowquinn** [comment]
Hi Pavlo,

Thank you for your interest in `pyani`.

The first thing that might help you here is that `conda` installs version 0.2.10, which does not have the `pyani` command/program. For that version you must use `average_nucleotide_identity.py`. 

You had previously indicated that you were using `pyani` v0.3.0-alpha, which does provide the `pyani` command/program, but also provides the `average_nucleotide_identity.py` command for backwards-compatibility with v0.2.10 that is in wider use. I was assuming that you would still be using v0.3.0-alpha. If you then installed `pyani` using `conda`, then I would expect v0.2.10 to take priority in your `$PATH`.

So, the first thing to do is confirm which version of `pyani` you are using, and then use the command appropriate to that version.

- v0.2.10 usage: [https://github.com/widdowquinn/pyani/blob/master/README_v_0_2_x.md](https://github.com/widdowquinn/pyani/blob/master/README_v_0_2_x.md)
- v0.3.0 usage: [https://pyani.readthedocs.io/en/latest/](https://pyani.readthedocs.io/en/latest/)

Another thing that might help is to keep versions of `pyani` separate. It sounds like you've installed `pyani` using two different methods: from source (v0.3.0-alpha) and with `conda` (v0.2.10). This may have introduced conflicts in the installed libraries, leading to the second error you see (`ModuleNotFoundError: No module named 'pyani.scripts'`). I can't fully diagnose that from here, but I can suggest using `conda` to uninstall the `bioconda` version of `pyani`, and then downloading the source for v0.3.0-alpha (the fix is now implemented), and installing that way, again. This should give you v0.3.0-alpha (which is not entirely complete, but works for ANIm).

Alternatively, you might like to create a new `conda` environment, and install `pyani` directly in that. This should install v0.2.10 (which is stable) in the `conda` environment.

I hope that these suggestions help.

L.

**Comment by pavlo888** [comment]
Hi Leighton,

Alright, I understand. 

I have created a new environment and installed it from source and it works!!! Thanks for your help. 

Cheers, 

Pablo

**Comment by widdowquinn** [comment]
Brilliant! I'm so glad it's working for you!

Apologies for the long transition period - it's leading to more confusion than I'd like.

Stay safe!

L.
