### ISSUE TITLE
Question about reusing blast results to speed up processing

### ISSUE THREAD

**Issue by louellette** [widdowquinn/pyani#184]
#### Summary:
Is there a workflow that reuses blast results to speed up re-runs? Or any other suggestion to speed up workflow?

#### Description:
I'm running ANI for many metagenomic assembled genomes (MAG).  I include up to 20 genomes from PATRIC or NCBI along with my MAG using my best guess as to the species of the MAG.  I'm using ANIb because I could be way off on my species guess and I find that ANIb is more accurate.  There are two situations where reusing the blast results would be helpful.  One is the situation where I just revise my guess and add or remove a few of the 20 other genomes and use the same MAG.  The other is when I find the next MAG that is similar. I see the blast results stored in my directory and I wonder if there is a way to reuse them to save time.

PS - Thank you for this software!  It has been very helpful to me.

#### pyani Version:
0.2.9

#### installed dependencies
If you are running a version of `pyani` v0.3 or later, then please run the command `pyani listdeps` at the command line, and enter the output below.

#### Python Version:
Python 3.7.4
#### Operating System:
Description:	Ubuntu 16.04.6 LTS xenial

**Comment by widdowquinn** [comment]
Hi @louellette - I'm so pleased you're finding `pyani` useful.

There are two ways to reuse BLAST (or other alignment) results. One is implemented in v0.2, and the other in v0.3.

In v0.2, you can reuse BLAST output and skip recalculation, with the `--skip_blastn` argument. Unfortunately, you can't use this to incrementally add genomes or use different combinations - which is what you're looking to do. I made a bad design choice for reusability, and this was a strong motivation for the restructuring of v0.3.

In v0.3, all results are stored in a local SQLite database and, if `pyani` detects that a calculation has already been performed (it checks aligner version and parameter settings, BTW - if you update BLAST you'd want to recalculate), it will reuse those results rather than scheduling a job. This makes it possible to - among other things - combine databases, or perform incremental additions to the dataset over time, only recalculating results for the new genomes.

v0.3 is in alpha though, and has a number of outstanding issues before it's ready for release (at the moment I'm the only developer, so it's all my fault!) but it does work, and if you'd like to try it out I'd love the feedback. ANIm is more reliably implemented than ANIb, right now.

To use v0.3 you'll have to install from source. I'd recommend doing that in a new `conda` or other virtualenv. Please do come back with any questions, bug reports or suggested fixes!

L.

**Comment by louellette** [comment]
Thank you for your quick reply.  I will keep an eye out for when you implement the ANIb method in v0.3 and give it a go.
