### ISSUE TITLE
Create phylogeny tree

### ISSUE THREAD

**Issue by noeldjitro** [widdowquinn/pyani#186]
Is there a way to create a phylogeny tree in Newick format from pyani output?

Thanks

**Comment by widdowquinn** [comment]
Hi Noel,

Thanks for using `pyani`!

`pyani` doesn't currently output tree data directly (though it is calculated as part of the heatmap generation) - adding that feature is a good idea, and I'll start a new issue for it.

One note of warning: I wouldn't treat any tree `pyani` generates as a *phylogenetic* tree - they're all built from pairwise distance matrices, where the distances may be calculated from different sets of sites in each genome; furthermore no evolutionary model mechanism is fit to the data. Because of this, I'd recommend you use a multigene tree with a properly-fit model for a real *phylogeny*.

However, the `pyani` results are genuine similarities, and it is appropriate to view them as a dendrogram. To do this (at the moment) I would import one of the distance matrices produced  by `pyani` and apply a clustering method. You could do this in `R` with something like (untested code):

```R
library(ape)
my_dists = read.table("pyani_ani.tab", header=T, sep="\t")
my_cluster = hclust(dists, method="complete")  # Note: other clustering approaches are possible
my_tree = as.phylo(cluster)
write.tree(my_tree, "pyani_ani.new")
```

**Comment by widdowquinn** [comment]
I'm closing this question for now - please comment on #187 if you'd like to continue the discussion.
