### ISSUE TITLE
Multiple array jobs submitted to SGE out of order

### ISSUE THREAD

**Issue by peterjc** [widdowquinn/pyani#22]
I presume each array job is limited to 10000 child-jobs due to an SGE limitation, and therefore when there are more pairwise comparisons pyani creates multiple array jobs, here seven:

Using v0.2, e.g.

```
$ ~/repositories/pyani/average_nucleotide_identity.py -i fetch_taxa/ -o big_test --scheduler SGE
Your job-array 13782.1-10000:1 ("ANI_5") has been submitted
Your job-array 13783.1-10000:1 ("ANI_1") has been submitted
Your job-array 13784.1-10000:1 ("ANI_6") has been submitted
Your job-array 13785.1-10000:1 ("ANI_2") has been submitted
Your job-array 13786.1-2481:1 ("ANI_7") has been submitted
Your job-array 13787.1-10000:1 ("ANI_3") has been submitted
Your job-array 13788.1-10000:1 ("ANI_4") has been submitted
...
```

Expected output would be to submit the jobs in order,

```
$ ~/repositories/pyani/average_nucleotide_identity.py -i fetch_taxa/ -o big_test --scheduler SGE
Your job-array 13782.1-10000:1 ("ANI_1") has been submitted
Your job-array 13783.1-10000:1 ("ANI_2") has been submitted
Your job-array 13784.1-10000:1 ("ANI_3") has been submitted
Your job-array 13785.1-10000:1 ("ANI_4") has been submitted
Your job-array 13786.1-10000:1 ("ANI_5") has been submitted
Your job-array 13787.1-10000:1 ("ANI_6") has been submitted
Your job-array 13788.1-2481:1 ("ANI_7") has been submitted
...
```

**Comment by widdowquinn** [comment]
I'll look at it - could be a simple change (so long as it's not SGE-induced).

**Comment by widdowquinn** [comment]
Looking at the code, I think that job arrays are submitted in numerical order, and the out of order runs may be due to SGE scheduling, rather than `pyani`. I've added some more informative log messages to see what might be going on, but haven't been able to reproduce what you saw:

```
INFO: Jobs passed to scheduler in order:
INFO: 	ANIm_Phytophthora_1
INFO: 	ANIm_Phytophthora_2
INFO: 	ANIm_Phytophthora_3
Your job-array 13806.1-1000:1 ("ANIm_Phytophthora_1") has been submitted
Your job-array 13807.1-1000:1 ("ANIm_Phytophthora_2") has been submitted
Your job-array 13808.1-16:1 ("ANIm_Phytophthora_3") has been submitted
```

There's also now a new argument `--SGEgroupsize` that allows you to modify the job array size on SGE, should you wish (commit [682e6](https://github.com/widdowquinn/pyani/commit/682e62d3f641aa0158c401f771590cf6bb1c1fce)).

I'll reopen the issue if the weird ordering is due to `pyani`.
