### ISSUE TITLE
nucmer_output intermediate files

### ISSUE THREAD

**Issue by peterjc** [widdowquinn/pyani#220]
#### Summary:

Running ``pyani anim input_dir output_dir ...`` on *N* genomes creates *N^2* under ``output_dir/nucmer_output/`` which scales badly with hundreds on inputs, noted on #147.

Removing the files are loading into the DB would help but we would loose the useful ``--recovery`` functionality.

@widdowquinn how do you feel about the following ideas (which both could be implemented).

#### Idea 1(a):

Combine the nucmer and delta-filter steps into one (half the cluster jobs too, currently have ``PYANI_deps`` and ``PYANI_main``), and only keep the final output. This would mean half the intermediate files, i.e. *0.5 N^2* files.

#### Idea 1(b):

A less invasive change, write the nucmer output to temp/scratch (would have to be available to all the cluster nodes), and only the delta filtered copy to ``output_dir/nucmer_output/`` - again halving the stored intermediate files.

#### Idea 2:

Use a nested structure, so rather than rather than ``output_dir/nucmer_output/A_vs_B.*`` we have ``output_dir/nucmer_output/A/A_vs_B.*`` to avoid the *N^2* scaling in any one folder.

**Comment by widdowquinn** [comment]
I've been thinking about this for a while, but I'm not sure it's documented in detail beyond #147 - but my thoughts are:

**`--recovery` functionality** - this is only necessary at the moment because we (1) run all the comparisons then (2) bring them into the database. If we "compare then import" for each comparison, we need only check which comparisons are present in the database, and `--recovery` isn't necessary any more. My favoured option is to "compare and import" for each comparison job, and delete all the comparison files by default after import.

**Idea 1(a):** IIRC the `nucmer`/`delta-filter` jobs were originally carried out as a single command - like you suggest - but later SGE/OGE scheduler implementations broke the way I was doing it. The current `delta_filter_wrapper.py` solution is a hacky way of getting that functionality back. There may be a better way of doing this along the lines you suggest… I wonder if `&&` works for this?

**Idea 1(b):** that's almost what I'm proposing in #147 - only we wouldn't keep the filtered output. I'm not opposed, but I think the immediate database import would remove the need to keep the filtered output.

**Idea 2:** that does avoid the scaling issue of number of files in a directory, but it still litters the filesystem and takes *ages* to compress/decompress/delete/back up etc. I'm still inclined to delete the `MUMmer` output as early as possible in the process.

I may be missing something, though.

**Comment by peterjc** [comment]
I think I have idea 2 working locally, this is a minimal change and makes a big difference with ~500 genomes. I hope you'll accept a pull request for this as a significant short term improvement.

I agree long term it would nice not to need ``--recovery``

**Comment by widdowquinn** [comment]
What sort of improvement are you seeing with your implementation? Speed?

**Comment by peterjc** [comment]
Still some niggles with loading the filtered delta files into the DB, so no direct comparisons to offer.

**Comment by peterjc** [comment]
Found the problem in my work on nested directories for the nucmer files, cross reference #217.

**Comment by peterjc** [comment]
We could close this with idea 2 (nested folders) merged as part of #217?

Or leave this open to address idea 1 to avoid storing so many intermediate files?

**Comment by baileythegreen** [comment]
@widdowquinn Nested folders in anim are implemented as a result of this discussion. Do we want to go for one of the other options suggested by Peter, something else, or close this?
