### ISSUE TITLE
Results ANIm vs ANIb considerably different, no nice diagonal in ANIb

### ISSUE THREAD

**Issue by bastian-wur** [widdowquinn/pyani#223]
#### Summary:
I ran pyANI twice, one with ANIb, then with ANIm. The results are different, and there's no nice diagonal in the ANIb output.
I am also aware that blast A vs B will give slightly different results than blast B vs A, but I would not have expected such a difference.

ANIb:
![ANIb_percentage_identity](https://user-images.githubusercontent.com/5961134/93000843-44822480-f52b-11ea-8ed6-7a712705ddeb.png)

As you can see, the diagonal is messed up in e.g. the top right.
This is not right like this, is it?

ANIm:
![ANIm_percentage_identity](https://user-images.githubusercontent.com/5961134/93000847-4e0b8c80-f52b-11ea-9a61-002fa072830b.png)

As you can see, here I have a diagonal.
But I'd expect that the result is roughly the same, independent of method, no?

This ANIm also does not look exactly like it should.
E.g. if you look at the ANIb, on the bottom left, there's a group of Desulfitobacterium hafniense. You don't see these grouped together in the ANIm, they are distributed through the image.

-> I am worried about this output.
Any recommendations?

#### used command:
average_nucleotide_identity.py -o /media/Transcend/strain_L/external_data/pyani_result/ -i /media/Transcend/strain_L/external_data/genomes/ -v -g -m ANIb --workers 7
Only changed ANIm

#### pyani Version:
0.2.10
#### Python Version:
3.8.3
#### Operating System:
Ubuntu 19.10
#### blast version
2.5.0
#### nucmer version
3.1

**Comment by widdowquinn** [comment]
Hi Bastian,

Thanks for your interest in `pyani` - there's a lot to unpack in your questions. I'll do my best to answer them.

> I ran pyANI twice, one with ANIb, then with ANIm. The results are different, and there's no nice diagonal in the ANIb output

It's best not to focus on the diagonal. From the plots it appears that your dataset is quite obviously of several different groups of organisms whose pairwise comparisons occasionally show "no similarity" in the sense that either BLAST or MUMmer (or both) could not find any regions of sequence similarity. An ANI comparison between such genomes is not advisable.

This affects the heatmap output in part because the dendrograms/row and column ordering are calculatated using the similarities of the complete distribution of (here, percentage identity) results for each genome. The high-identity numbers contribute, but so do the low-identity numbers. When extremely-distantly-related genomes, such as yours, are compared this can give the heatmaps some strange appearances. That may include splitting your *D. hafniense* group so they are not a coherent square on the diagonal. My suspicion is that the primary reason for this is that MUMmer is more sensitive to distant similarities than BLAST (hence more blue, rather than grey, squares), and these small values are causing individuals of that group to be clustered with inappropriate other genomes. I can see by eye that the "high similarity" cells will probably group those isolates together if you reorganise your input dataset.

I would advise dividing your input dataset into groups that contain only genomes that are certain to be related at the genus level. This is not always reliably recorded in NCBI taxonomy (but GTDB does a better job). I have found whole genome comparisons to be much better indicators of taxonomic classification than phenotype.

I would recommend that you approach your dataset by first looking at the coverage plot. This will help you identify groups of organisms that share at least 50% of their genome. These are likely to be the same genus. Then produce separate ANI analyses for the each of those organism groupings.

If you do this, I would expect that you will recover the kinds of groupings you expect, and also find some interesting new relationships.

I'd love to see the results of splitting your dataset in this way, if you're happy to share the figures.

**Comment by bastian-wur** [comment]
Ah, mmhh, I already had the feeling that the NaNs could be involved in this issue :/.

Okay, I've now re-run this with only one genus from the bigger picture. (but I forgot, no doubles in there, so can't really confirm the result, meh). 
The identity plots are solidly blue, so that should not be a problem, also alignment lenghts look fine. The alignment coverage plots have a partially botched diagonal, but the values there also all seem to be around 30%, which I guess that explains this.

-> so I guess there's nothing strange to report here at the end, no?

(also sorry for this on a Saturday evening)

**Comment by widdowquinn** [comment]
Just before I close this (apologies for the delay!) I want to note that we shouldn't expect the coverage plots to have red squares (or other structures) down the diagonal in all cases. Coverage is not symmetrical - one genome may align over 100% of its length to only 80% of another genome, for example - the difference can be due to any of several factors, but different plasmid complements are one possible cause.
