### ISSUE TITLE
fail to run ANIm

### ISSUE THREAD

**Issue by liuqian666** [widdowquinn/pyani#224]
#### Summary:
I try to use pyani to calculate ANIb and ANIm. ANIb was successful but ANIm was always fails.
And I've re-installed pyani through Conda. It didn't work. Here are the errors:

#### Description:
$ average_nucleotide_identity.py --indir /media/epi-linux/8t/2_liuqian/Actino_fna --outdir /media/epi-linux/8t/2_liuqian/ANI/ANIm/actino_ANIm_output -m ANIm -g
![image](https://user-images.githubusercontent.com/57260099/96395869-532dbc80-11f8-11eb-9033-7fd9c45ece84.png)

#### Reproducible Steps:
$ average_nucleotide_identity.py --indir /media/epi-linux/8t/2_liuqian/Actino_fna --outdir /media/epi-linux/8t/2_liuqian/ANI/ANIm/actino_ANIm_output -m ANIm -g

#### Current Output:
![image](https://user-images.githubusercontent.com/57260099/96395869-532dbc80-11f8-11eb-9033-7fd9c45ece84.png)
![image](https://user-images.githubusercontent.com/57260099/96395925-7ce6e380-11f8-11eb-97dc-2f80f5b0e1d1.png)

![image](https://user-images.githubusercontent.com/57260099/96395977-9daf3900-11f8-11eb-8e89-111f5cbdd889.png)

#### Expected Output:
All identities between the strains shouldn't be 1
most of them should between 0 ~ 1

#### installed dependencies
If you are running a version of `pyani` v0.3 or later, then please run the command `pyani listdeps` at the command line, and enter the output below.

When I run the command `pyani listdeps` or 'average_nucleotide_identity.py listdeps', no list shows.
![image](https://user-images.githubusercontent.com/57260099/96396211-4198e480-11f9-11eb-9331-e4614dd2ec8b.png)

**Comment by widdowquinn** [comment]
Hi @liuqian666 

Thank you for using `pyani` and reporting this issue.

Looking at the species names, I suspect the issue might stem from the input genomes being too distant from each other to give a meaningful result: actinomycetes are much more genome-diverse than the taxonomy might imply. This causes `nucmer` comparisons - as you report - to "fail" because it can't find enough homologous sequence to align.

Although ANIb gives "a result" I expect that if you inspect the coverage output, the percentage coverage of each comparison is very close to zero.

If that's not the case, or if you aren't sure how to proceed to test the suggestion that the genomes are not significantly similar, then please do attach a couple of genome examples to this issue thread and I'll take a look.

Cheers,

L.
