### ISSUE TITLE
Find genomes causing Blast to fail

### ISSUE THREAD

**Issue by nclaesnacw** [widdowquinn/pyani#241]
Thanks for pyani.
With WARNING: At least one Blast run failed. ANIb may fail. 
Sometimes it does and sometimes it doesn't, but in either case it would be useful to identify the culprit genomes.
One can imagine they may be too distant or too fragmented.
But is there a way to identify which one's have failed?
Thanks

**Comment by widdowquinn** [comment]
Hi @nclaesnacw - thanks for your interest in `pyani`.

BLAST (or the other comparison tool) jobs can fail for a number of reasons, but the current job management code doesn't do more than test whether they've all passed. We'll be working on improving that to direct users towards particular comparisons with problems, over the next year or so. But for now, there's nothing in `pyani`'s code to do that.

If the issue is with genomes being too distantly related, this can show as the pairwise comparison output file being empty. These are named so that you can tell the genomes that were being compared. A check on file size (or `wc`) for the output files will probably help identify the problem comparisons.

I hope this helps - sorry there's not something more useful in the code, just yet.

L.

**Comment by nclaesnacw** [comment]
So, with a large dataset one way to isolate the cculprits, and save waiting until the end of a long run to find it has failed, would be to do in blocks and use the database facility to accumulate the data. However, in v2.10 I see no evidence of an sqlite db - do I need a later version?

**Comment by widdowquinn** [comment]
The SQLite db is only used in v3, and ANIb is not yet working in that version (I always recommend ANIm - it's much faster and give symmetrical output so A vs B has the same result as B vs A for %identity)

I'm not sure I'd bother doing the analysis in blocks, myself.

With `pyani` v0.2, you should be able to use the `--noclobber` and `--force` options with `average_nucleotide_identity.py` and in this case `pyani` will attempt to rerun all jobs in the same directory, but not rerun those for which output files already exist. You could delete the "faulty" output files and - assuming that the problems with the comparison were corrected - the analysis should only rerun the missing comparisons.

Alternatively, you could substitute manually-run output for the faulty files. But that's not very reproducible…

If you're in v3, there is a `--recovery` option that I think does work (tests are missing right now, I think). So long as you don't delete the existing output between runs, you can pass the `--recovery` option. With this, `pyani` checks the output directory for existing output as well as checking the SQLite database. So…

```bash
pyani anim genome_dir output_dir
```

would run all analyses that had no result in the existing database, but

```bash
pyani anim --recovery genome_dir output_dir
```

should check the database and also the comparison file output directory for an existing output file in each case, and not rerun analyses that it didn't have to.

I hope this helps a wee bit.

**Comment by nclaesnacw** [comment]
Thanks a lot

**Comment by nclaesnacw** [comment]
Hi
ANIm lists all the pairwise comparisons which have no alignment :-)
I was asking the question 'how close are these candidate related genomes' (from 16S, MLST, literaature).
I prefer ANIb for consistency with my use of the ANI calculator from the Kostas lab which I previously identified as my preferred method. I understand Blast and ANIb - A vs B is not the same as B vs A. The histogram of fragmnet similarities, at Kostas, is useful too - is there data in the blast output to generate those?
In both ANIm and ANIb it would be useful, I think, for pyani to accept 'no alignment' or 'blast fail' as a result, rather than an error, and put a zero in the matrix (and carry on)?

**Comment by widdowquinn** [comment]
Hi @nclaesnacw 

You might not be surprised to know I have opinions about how to do ANI well ;)

I do discourage ANIb for more reasons than just the asymmetry (the asymmetry is a deal-breaker for me: it makes no sense to say that A is more similar to B than B is to A), but other issues include:

- the ANIb result is unstable to the choice of fragment break-point
- the requirement that a minimum proportion of each fragment participates in a match, rather than using all the information available in homologous regions

ANIm does not have these problems, and is much quicker.

I don't find it useful to produce a histogram of fragment similarities, as this is a result that is dependent both on the similarity of the organisms *and* the fragmenting parameters (start base, fragment size, how you handle sequence ends, etc.) and isn't that helpful, as a result. It's not something I plan to add. You could reconstruct this from the BLAST output, if you needed to.

The problem with recording a comparison failure as "zero" is that it is indistinguishable from cases where the true value for the matrix is "zero," which does sometimes happen. The results would have to be recorded as `NA`/`NULL` or something equivalent, and that can cause problems with the downstream calculations and visualisation.

With the new model for v3, where results are written to a local database, there is no major computational cost to re-running previous comparisons. Rather than include a potentially misleading value in the results table, I think returning the warning so that the user can deal with it (fix a filename, remove the genome from analysis, etc.) and re-run the analysis is the right way to go.
