### ISSUE TITLE
Where should we discuss issues about the pyani repo?

### ISSUE THREAD

**Issue by widdowquinn** [widdowquinn/pyani#283]
@widdowquinn Can we figure out some place to have discussions about this repo that is still tied to it (unlike email and Signal) but doesn't make use of Issues or require a Pull Request?

**Comment by widdowquinn** [comment]
I'm happy to consider options. I think GitHub Issues/PRs have some advantages for discussion of repository issues:

- they are linked to the repository
- they are preserved and searchable
- they are transparent and open for public comment

What do you see as the disadvantages of using these, and what are the advantages of using another platform?

I'd like to keep the number of platforms I need to monitor to a minimum (I have eight open on my screen right now), and think I would need motivation to introduce another.

**Comment by baileythegreen** [comment]
The options I am aware of that are tied to GitHub, and a few points about them:

- Repository Discussions tab:
    - must be enabled by repo owner (i.e., not me)
    - I believe these are public
- Team discussions on GitHub:
    - would require creation of a pyani 'team'
    - unclear if this can be done outwith a GitHub organisation
- Gitter
    - can be tied to a specific repo, which allows for easy linking to PRs/Issues
- GitHub Projects
    - seems suboptimal as a conversation locale


I originally added this request to the project when I ran into the issues with SQL in the `fastANI` implementation. A PR didn't seem right because the branch was not at a point where making a PR seemed sensible — it was not operating correctly, and was missing tests. An Issue also seemed wrong because it wasn't related to `pyani` usage so much as development.

I understand all of the advantages provided by PRs/Issues, It just doesn't quite feel like they fit development questions. Maybe an alternative Issue template would help.

**Comment by widdowquinn** [comment]
I didn't know about GitHub Discussions - that looks great, and just what we need! Thanks for suggesting it!

I've enabled Discussions on this repo now. Let's try that for a while and see if it meets our needs. If not, we can revisit this, later.
