### ISSUE TITLE
pyani does not run

### ISSUE THREAD

**Issue by Rodolph235** [widdowquinn/pyani#339]
Hi, thanks for helping. 
I installed pyani with conda (I am using miniconda2) in a python 3.7 environment that I already had created. The installation went smoothly without apparent erros but when I test by typing pyani -h:
(base) Users-iMac:~ Albano$ conda activate py37
(py37) Users-iMac:~ Albano$ pyani -h
-bash: pyani: command not found
Any ideas to why this is happening will be very appreciated. 
Thanks a lot
Best
Rodolpho

**Comment by baileythegreen** [comment]
Hi @Rodolph235, thank you for your interest in `pyani`!

From what you describe I see a few possible issues:
1. `conda` should install version 2 of `pyani`, but you are using the version 3 command line interface;
1. `pyani` has not been added to your PATH (or not as the name you are using because of 1); or
1. there is also a chance `miniconda2` will have used Python 2 to create your environment if you did not specify Python 3.

Please share the following so I can determine which of these are true:

- the specific command you used to create your `conda` environment
- the output of `python --version`
- the output of `average_nucleotide_identity.py -h`
- the output of `echo $PATH`

**Comment by Rodolph235** [comment]
Hi @baileythegreen,
Thank you for the prompt response. I resolved the issues by installing in a virtual box ubuntu environment with Miniconda3. I was trying to install before on a mac running high sierra OS. Thanls a lot. 
Best
Rodolpho
