### ISSUE TITLE
anim nested tree recovery mode follow up

### ISSUE THREAD

**Issue by peterjc** [widdowquinn/pyani#353]
In testing #351 in order to re-run an analysis from last year (August 2020) with the existing ``nucmer_output/`` folder, and different subsets, a small test case finished fairly quickly. A large subset of about 454 entries (out of the original approx 500) has not. Running ``top`` shows it is calling ``nucmer`` and examination of the ``nucmer_output/`` folder shows new/modified files.

Excerpt from the 17 genome example, note 17*16/2 = 136:

```
...
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Generating ANIm command-lines
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Compiling genomes for comparison
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Compiling pairwise comparisons (this can take time for large datasets)...
100%|██████████| 17/17 [00:00<00:00, 387517.22it/s]
[INFO] [pyani.scripts.subcommands.subcmd_anim]: 	...total parwise comparisons to be performed: 136
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Checking database for existing comparison data...
[INFO] [pyani.scripts.subcommands.subcmd_anim]: 	...after check, still need to run 136 comparisons
[WARNING] [pyani.scripts.subcommands.subcmd_anim]: Entering recovery mode
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Recover mode identified 210692 existing output files for reuse: <snip>.filter (etc)
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Creating NUCmer jobs for ANIm
100%|██████████| 136/136 [00:00<00:00, 526.72it/s]
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Running jobs with multiprocessing
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Multiprocessing run completed without error
[INFO] [pyani.scripts.subcommands.subcmd_anim]: ...jobs complete
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Adding comparison results to database...
100%|██████████| 136/136 [00:05<00:00, 25.95it/s]
[INFO] [pyani.scripts.subcommands.subcmd_anim]: ...database updated.
[INFO] [pyani.scripts.pyani_script]: Completed. Time taken: 22.073
...
```

This does not say how many of cached files are of interest (most are from other genomes not needed here), and how many times ``nucmer`` will be called.

A more elaborate test may be needed to verify no ``nucmer`` calls are made when the cached output should already be complete.

I suspect a glitch in path comparison (e.g. relative vs absolute paths), and the current tests passed doing unnecessary re-computation.

Update: typo

**Comment by baileythegreen** [comment]
Hi @peterjc,

I agree, the `logger.info` output does not make it very clear whether existing comparisons are being re-run, however, from the time taken for the run, I think it is unlikely that they are.

If you were to run the same command with the `--debug` option (and, a log file), you will get some more informative lines from lines 349-350 in `subcmd_anim.py` that should clearly say one way or the other:

```python
    if args.recovery and outfname in existingfiles:
        logger.debug("Recovering output from %s, not submitting job", outfname)
```

I will look into adding some additional `logger.info` lines that give a clearer idea that previous comparisons are being used, but without spamming the user.

If you see from the debugging output that comparisons are indeed being rerun, let me know. That would indicate a problem.

**Comment by peterjc** [comment]
Thanks - I will explore this in debug mode, but agree something like adding a breakdown of the new jobs vs recovery jobs to the default logging would be informative.

**Comment by baileythegreen** [comment]
So, a few things based on what I'm seeing in my tests (note: I've not used the recovery mode a lot before because I've been developing new features, so I've been exploring it today. I hope I'm not just telling you things you already know.):

- If you use the `--recovery` flag, the `Recover mode identified <##> existing output files for reuse: <file>.filter (etc)` line gets printed. Period.
- If you use `--recovery` AND `--debug` AND there are results files for comparisons that do not exist in the database, the `[DEBUG] [pyani.scripts.subcommands.subcmd_anim]: Recovering output from <file>.filter, not submitting job` line gets printed.
    - This is the case, for instance, when supplying a new (empty) database. (The only way I can get that part to run, actually.)
- If you use `--recovery` AND `--debug` BUT there is no results file for a comparison that does not exist in the database, the `[DEBUG] [pyani.scripts.subcommands.subcmd_anim]: Building job` line gets printed.
- If you use `--recovery` BUT the results are all already in the database, recovery doesn't do anything because those comparisons have already been noted as unnecessary to run.

The process is:
- We start from a list of all possible comparisons given the input: `comparisons`.
- Then we remove any in the database, giving: `comparisons_to_run`.
- If recovery mode is used, we create a list of output files (these should be named as: `${args.outdir}/nucmer_output/*/*.filter`.
- Then, if recovery mode is used, we see if we already have the results: `existing_files`, and remove matching comparisons from `comparisons_to_run`.
- Then we run whatever is left.

***

I've added some logging lines to produce the following (examples from two different runs):
```
[INFO] [pyani.scripts.subcommands.subcmd_anim]: No results found for 16 comparisons; 16 new jobs built.
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Retrieving results for 0 previous comparisons.

[INFO] [pyani.scripts.subcommands.subcmd_anim]: No results found for 29 comparisons; 29 new jobs built.
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Retrieving results for 91 previous comparisons.
```

The code can be found on the `issue_353` branch. See if that suits your purposes.

I kind of glossed over this part of your original post because I focused on the time taken in the small example you posted:
> A large subset of about 454 entries (out of the original approx 500) has not.
so, depending on whether the comparisons all existed in the database already, and your computer's specs, this may still indicate a different problem.

**Comment by peterjc** [comment]
The extra logging on your branch appears to confirm all 136 existing nucmer files are used on the 17 genome example:

```
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Generating ANIm command-lines
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Compiling genomes for comparison
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Compiling pairwise comparisons (this can take time for large datasets)...
100%|██████████| 17/17 [00:00<00:00, 347820.33it/s]
[INFO] [pyani.scripts.subcommands.subcmd_anim]: 	...total parwise comparisons to be performed: 136
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Checking database for existing comparison data...
[INFO] [pyani.scripts.subcommands.subcmd_anim]: 	...after check, still need to run 136 comparisons
[WARNING] [pyani.scripts.subcommands.subcmd_anim]: Entering recovery mode
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Recover mode identified 210692 existing output files for reuse: enterobase_cladeV_anim/nucmer_output/GCF_000005845.2_ASM584v2_genomic/GCF_000005845.2_ASM584v2_genomic_vs_GCF_000006925.2_ASM692v2_genomic.filter (etc)
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Creating NUCmer jobs for ANIm
100%|██████████| 136/136 [00:00<00:00, 476.36it/s]
[INFO] [pyani.scripts.subcommands.subcmd_anim]: No results found for 0 comparisons; 0 new jobs built.
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Retrieving results for 136 previous comparisons.
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Running jobs with multiprocessing
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Multiprocessing run completed without error
[INFO] [pyani.scripts.subcommands.subcmd_anim]: ...jobs complete
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Adding comparison results to database...
100%|██████████| 136/136 [00:05<00:00, 25.59it/s]
[INFO] [pyani.scripts.subcommands.subcmd_anim]: ...database updated.
```

I would tweak the wording a little, but something like this does seem helpful when using ``--recovery`` mode.

As to my larger dataset, it looks like my cache of nucmer files may be incomplete - with about a quarter needing to be run:

```
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Generating ANIm command-lines
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Compiling genomes for comparison
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Compiling pairwise comparisons (this can take time for large datasets)...
100%|██████████| 454/454 [00:00<00:00, 2800314.73it/s]
[INFO] [pyani.scripts.subcommands.subcmd_anim]: 	...total parwise comparisons to be performed: 102831
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Checking database for existing comparison data...
[INFO] [pyani.scripts.subcommands.subcmd_anim]: 	...after check, still need to run 102831 comparisons
[WARNING] [pyani.scripts.subcommands.subcmd_anim]: Entering recovery mode
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Recover mode identified 210692 existing output files for reuse: enterobase_cladeI_anim/nucmer_output/GCF_000005845.2_ASM584v2_genomic/GCF_000005845.2_ASM584v2_genomic_vs_GCF_000006925.2_ASM692v2_genomic.filter (etc)
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Creating NUCmer jobs for ANIm
100%|██████████| 102831/102831 [02:35<00:00, 659.20it/s]
[INFO] [pyani.scripts.subcommands.subcmd_anim]: No results found for 23541 comparisons; 23541 new jobs built.
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Retrieving results for 79290 previous comparisons.
[INFO] [pyani.scripts.subcommands.subcmd_anim]: Running jobs with multiprocessing
```

The good news is lots of the files are being reused, that shows there is no problem with the path matching.

My next guess is that something as changed in the sorting for the ``A_vs_B`` filename stem (as opposed to ``B_vs_A``), but perhaps my cache really is incomplete? I will investigate further.

**Comment by baileythegreen** [comment]
Because ANIm is symmetric (meaning running A_vs_B and B_vs_A gives the same output), each pair of genomes is only run as one comparison, to reduce the number of jobs; I'm sure you know this.

However, this may have implications on the recovery. We create a list of pairs using `itertools.combinations()`, and for actually running ANIm the order of those doesn't matter. (For other subcommands we use `itertools.permutations()`, which takes order into account.) Where there might be an issue with this approach is in the naming of the output file. We construct the file name like this: `f"{fname1.stem}_vs_{fname2.stem}"`, using the pair of genomes from `combinations()` — `(fname1, fname2)`. When we check for output files for comparisons not in the database, we look for the *expected* output file name, generated using the same construction—which means if the two genome names are swapped, it won't match.

I would like to think that the way the genomes are loaded into the database and subsequently pulled from it to create the genome pairs always happens the same, but I can't say that for sure. And I think the implication of what you're saying is it might not.

**Comment by peterjc** [comment]
Yes, that's what I intend to check - if for example the names are built using a sorted list of input filenames, everything should be stable. If however the input order is whatever the filesystem returns, then recovery mode is not necessarily going to give the same order.

So I am expecting either the input file list gets sorted, or there is an alphabetic sort of the pair ``(fname1, fname2)`` before making filenames.

(While keeping in mind not all the comparison metrics are symmetric of course.)

**Comment by baileythegreen** [comment]
😕... The order in the names is supposed to reflect `reference_vs_query`, where that is relevant, and right now the code is not different for symmetric analyses like `ANIm`.

But, I think there's no reason why we couldn't alter the naming scheme for symmetric analyses to sort the names first, and so avoid this problem. It should make the behaviour more predictable, and that is a good thing.

I'll see about pushing a small change for that, and let you know so you can see if it solves the issue.

**Comment by peterjc** [comment]
Something has come up, so I’m not able to look into this today after all,
but I will.

**Comment by baileythegreen** [comment]
That's fine; I'm technically not working today, or tomorrow, anyway.

**Comment by peterjc** [comment]
Good news and bad news: This job finished in about 5 hours (using 32 workers on a single cluster node with multiprocessing), but that means I have destroyed the test case by computing the missing nucmer files.

However, it should be possible to test the theory about the order and thus nucmer file names depending on the FASTA file order on disk (which likely changed when this dataset was migrated between filesystems as part of a cluster upgrade).

Looking at the code in ``pyani/scripts/subcommands/subcmd_anim.py`` function ``subcmd_anim`` there is no explicit sorting of the filenames:

```python
    # Add information about this run to the database
    logger.debug("Adding run info to database %s...", args.dbpath)
    try:
        run = add_run(
            session,
            method="ANIm",
            cmdline=args.cmdline,
            date=start_time,
            status="started",
            name=name,
        )    
    ...

    # Get list of genome IDs for this analysis from the database
    logger.info("Compiling genomes for comparison")
    genomes = run.genomes.all()
    logger.debug("Collected %s genomes for this run", len(genomes))
```

I think it would suffice to add a ``sorted(...)`` call to function ``get_fasta_paths`` in ``pyani/pyani_files.py``

**Comment by baileythegreen** [comment]
I don't think you've entirely destroyed the test case. You could, for instance, create a new database, then submit the exact same run with `--recovery`. It may look for other swapped file names—which would certainly prove the problem. As would the existence of two files for the same genome pair whose names are just swapped. Have you verified that that is what happened?

`get_fasta_paths()` is called during use of the `index` subcommand, but this just creates the `md5` hashes and the `classes.txt` and `labels.txt` files—it doesn't touch the database at all, nor does it affect the order in which the other subcommands would "receive" files. `get_input_files()` should probably do it—this is where the subcommands get their source files from; or it could be sorted at the point you copy above `genomes = sort(run.genomes.all())`.

It is probably best to alter the `pyani_files.py` function, because then the issue should theoretically already be fixed for future symmetric subcommands.

**Comment by peterjc** [comment]
I agree there are multiple places the file/genome list might be sorted. I lean to the lowest level (in ``pyani_files.py``), or within the ``add_run`` function so that the DB entries are sorted.

Adding an assert within the anim main loop that file1 < file2 would be prudent - and I can try that with and without sorting the genome list. That would hopefully abort on an entry where I can confirm both file1_vs_file2 and file2_vs_file1 now exist on disk, and look at their dates.

**Comment by peterjc** [comment]
See pull request #355, and confirming that yes, I did find cases of both ``A_vs_B`` and ``B_vs_A`` comparisons on disk.

**Comment by baileythegreen** [comment]
> That would hopefully abort on an entry where I can confirm both file1_vs_file2 and file2_vs_file1 now exist on disk, and look at their dates.

Did you do this? I've been looking at this today, and if I'm right, I think the later file—the one `--recovery` attempts to find, doesn't, and then instructs the subcommand to create—will be the one where the genomes are incorrectly sorted?

**Comment by peterjc** [comment]
I added the assert on #355 first (before adding sorting), and confirmed it failed. That particular combination of files A and B was on disk twice from previous runs as both A_vs_B and B_vs_A.
