### ISSUE TITLE
why the clustering results are different in the two directions

### ISSUE THREAD

**Issue by magksi** [widdowquinn/pyani#368]
Hi, 
I'm wondering what is the reason that ANI heatmap is not symmetrical -> why the clustering results are different in the two directions?

this was a simple run with -m ANIb -g
All genomes are from the same genus, few complete genomes, most drafts.
pyani version 0.2
Python 3.7.8
I'm using Ubuntu 20.04.3 subsystem on Windows.

I'm attaching ANIb_percentage_identity 
![ANIb_percentage_identity](https://user-images.githubusercontent.com/77159108/148760671-9a330a61-1b82-4a2c-82f6-12437089adc0.png)

and ANIb_alignment_coverage.
![ANIb_alignment_coverage](https://user-images.githubusercontent.com/77159108/148760717-0e2e1d99-d2f2-42f8-b3a7-79e74ed0a31e.png)

Thank you in advance for the help interpreting these results :)

**Comment by widdowquinn** [comment]
Hi @magksi 

Thank you for your interest in `pyani`. The reason the results are asymmetrical is because the algorithm described in the [original manuscript introducing ANIb](https://www.microbiologyresearch.org/content/journal/ijsem/10.1099/ijs.0.64483-0#tab2) is inherently asymmetric and gives a different result when comparing genome A to genome B than it does comparing genome B to genome A.

In addition to this, coverage results are asymmetric because ANIb and ANIm only report similarities between detectably homologous regions in a pairwise analysis. The lengths of non-homologous regions (that don't participate in the ANI calculation) may differ between the genomes.

This question comes up occasionally, so you may find similar answers in the [closed issues](https://github.com/widdowquinn/pyani/issues?q=is%3Aissue+is%3Aclosed).

I hope this is useful and helps explain your observations.

L.

**Comment by magksi** [comment]
Hi @widdowquinn 

Thank you very much for your response, it is very helpful!
