### ISSUE TITLE
ANIm should not be symmetric

### ISSUE THREAD

**Issue by donovan-h-parks** [widdowquinn/pyani#373]
#### Summary:
PyANI treats ANIm as symmetric, but  the order of genomes impacts this calculation.

#### Description:
I have two test genomes. The ANIm results produced by PyANI change depending on the order these genomes are processed. That is, the results depend on which genome is considered the "reference" and which the "query" when running nucmer.

#### Reproducible Steps:
1. Process the attached genomes with PyANI using `average_nucleotide_identity.py -m ANIm --workers 1`.
2. Swap the names of the genomes (i.e. genome1.fna becomes genome2.fna and genome2.fna becomes genome1.fna).
3. Run PyANI again as in step 1, but changing the output directory.
4. Compare the results and observe that the ANIm values are now different. 

As a concrete results, the number of similarity errors changes from 512 to 561 depending on the order of the genomes.

### Expected Output:
[test_genomes.tar.gz](https://github.com/widdowquinn/pyani/files/7883433/test_genomes.tar.gz)

The ANI-percentage_identity.tab, ANIm_similarity_errors.tab, and ANIm_alignment_lengths.tab files are non-symmetric matrices that reflect which genome was the reference and which genome was the query.

#### pyani Version:
v0.2.11

#### Operating System:
Ubuntu

**Comment by widdowquinn** [comment]
Thanks @dparks1134 - apologies for the bug, and we'll deal with this as a priority.

Quick notes

- although it stems from the same misunderstanding of/assumptions about `mummer`'s operation, this is not the same issue as #340 and will probably not be fixed by the proposed changes to resolve that issue.
- the resolution currently appears to be to run `mummer` for the reciprocal pairwise comparisons.

L.

**Comment by widdowquinn** [comment]
NOTE: Handling under branch `issue_373`

**Comment by baileythegreen** [comment]
For reference, two sets of output for the genomes provided by @dparks1134, named `<reference>_vs_<query>.zip`.

[genome1_vs_genome2.zip](https://github.com/widdowquinn/pyani/files/7928527/genome1_vs_genome2.zip)
[genome2_vs_genome1.zip](https://github.com/widdowquinn/pyani/files/7928529/genome2_vs_genome1.zip)

**Comment by baileythegreen** [comment]
I have pushed changes to `issue_373` that remove the assumption that `ANIm` is symmetric; skip a test that fails if we no longer enforce genome sorting alphabetically as a result; and updated docs, so that they don't claim it is symmetric.

I will see if there are other things I have missed; in particular, I think perhaps the test outputs might need to be updated; (they pass, but this might just mean the differences fall within the designated tolerances)/

**Comment by widdowquinn** [comment]
> I think perhaps the test outputs might need to be updated; (they pass, but this might just mean the differences fall within the designated tolerances).

I think your guess is probably correct. It would be useful to have (for the record) a `pyani compare` output comparing (i) the old, symmetric behaviour and (ii) the new, non-symmetric behaviour so we can see how big the difference is for at least one real-world example we're familiar with.

**Comment by baileythegreen** [comment]
I tried uploading the archive of inputs I used here, but I think that must be too big; I've instead included the `classes.txt` file. @widdowquinn, it's a dataset you sent me, so you should already have the sequence files.

[classes.txt](https://github.com/widdowquinn/pyani/files/8409782/classes.txt)

Here's the output from running `pyani compare` on the symmetric and asymmetric versions of `anim`, using default settings. I have not yet addressed the suggestions made on `pyani compare` output in https://github.com/widdowquinn/pyani/pull/364, so apologies for the less-than-useful colour schemes, et cetera. I can add updated versions at a later date.

[summary_run1_vs_run2.md](https://github.com/widdowquinn/pyani/files/8409711/summary_run1_vs_run2.md)
[ref_1_vs_query_2_plots.zip](https://github.com/widdowquinn/pyani/files/8409720/ref_1_vs_query_2_plots.zip)

**Comment by baileythegreen** [comment]
It looks like *Dickeya didantii* NCPPB 898 chromosome, whole genome shotgun sequence specifically sees a lot of differences between the two.

**Comment by kiepczi** [comment]
I'm also marking this for closure, because my understanding is that this issue was fixed with [1f10a6c](https://github.com/widdowquinn/pyani/commit/1f10a6cd78e2d1dcee77f1cc4451cf5ea563841f).

Specifically, we have now decided to run two pairwise comparisons (forward and reverse), and calculate ANIm values for query for each comparison.
