### ISSUE TITLE
shebang of average_nucleotide_identity.py seems to be subjective 

### ISSUE THREAD

**Issue by jvollme** [widdowquinn/pyani#59]
Just a minor issue: I just installed the current version of pyani via pip. This version includes this shebang, which seems to point to a developers subjective python location:
`#!/Users/lpritc/Development/GitHub/pyani/venv-pyani/bin/python`

Maybe this should be changed to the more generally applicable  `#!/usr/bin/env python` or simply left out completely?

**Comment by widdowquinn** [comment]
Thanks for spotting and raising that!

It's correct in the source: [https://github.com/widdowquinn/pyani/blob/master/bin/average_nucleotide_identity.py](https://github.com/widdowquinn/pyani/blob/master/bin/average_nucleotide_identity.py) and in the `.tar.gz` source download

Creation of the `.egg` for distribution appears to have substituted the path that you see. I'll get a corrected version out ASAP.

**Comment by widdowquinn** [comment]
I've removed the PyPI egg and wheel while I try to track this down.

I've found some suggestions for the cause, e.g. at http://stackoverflow.com/questions/33792696/how-to-prevent-python-wheel-from-expanding-shebang - but I've not managed to fix the issue, yet.

**Comment by jvollme** [comment]
Well, it's only a problem for people not quite yet familiar with the linux command line, who would not know what to do with the "bad interpretor" error they would get. 
So maybe a workaround for now would be to adjust the documentation to instruct people to run the script using `python average_nucleotide_identity.py`? That should generally work.

**Comment by widdowquinn** [comment]
It's not possible to replace the old egg and wheel files for v0.2.2 with modified versions, so they are fully withdrawn, and a new version (v0.2.3) has been released, where the issue is corrected.

The problem seems to have been that a naive `python setup.py build` (or `python setup.py dist`) uses the immediately available `Python` executable *which is expanded even if the script itself has a generic location shebang*, and this needs to be overridden with a `python setup.py build --executable="<path to generic location>"`.

**Comment by widdowquinn** [comment]
I agree that it's not an unresolvable issue for those familiar with the command-line and `Python` interpreter errors ;)

Using `python average_nucleotide_identity.py` obviously works if you're in a directory with `average_nucleotide_identity.py` in it, but I'm hoping that publishing it as a script will enable even those who don't realise such a thing is possible to use it.
