### ISSUE TITLE
genbank_get_genomes_by_taxon.py seems to ignore "--format" argument

### ISSUE THREAD

**Issue by jvollme** [widdowquinn/pyani#89]
#### Summary & Description:
I am currently using pyani v.2.3 as installed via bioconda. `genbank_get_genomes_by_taxon.py` seems work generally for downloading contig-fastas.
However, when I try to download genbanks instead (which I need for some additional analyses), by setting the `--format` option to "gbk" (as stated in the help function), this argument seems to be ignored and i still just get the contig-fastas.

#### Reproducible Steps:
`genbank_get_genomes_by_taxon.py -t 1107 -l chloroflexuslog --email myemail@wherever.com -o chloroflexus --format gbk -v`

#### Current Output:
.fna & .fna.gz for each genome (BTW: I guess only the "*.fna.gz" files were actually meant to remain as final output here?) 

#### Expected Output:
.gbk[.gz] for each genome

#### pyani Version:
v2.3
#### Python Version:
v3.5.2
#### Operating System:
Linux Ubuntu 14.04
#### Summary & Description:
I am currently using pyani v.2.3 as installed via bioconda. `genbank_get_genomes_by_taxon.py` seems work generally for downloading contig-fastas.
However, when I try to download genbanks instead, by setting the `--format` option to "gbk" (as stated in the help function), this argument seems to be ignored and I still just get the contig-fastas.

#### Reproducible Steps:
`genbank_get_genomes_by_taxon.py -t 1107 -l chloroflexuslog --email myemail@wherever.com -o chloroflexus --format gbk -v`

#### Current Output:
.fna & .fna.gz for each genome

#### Expected Output:
.gbk[.gz] for each genome

#### pyani Version:
v2.3 (installed via bioconda)
#### Python Version:
v3.5.2
#### Operating System:
Linux Ubuntu 14.04

**Comment by widdowquinn** [comment]
Thanks John - I'll get on it.

**Comment by widdowquinn** [comment]
Hi John,

Thanks for the bug report - the root cause of the problem was that when I changed the internals to cope with the NCBI restructure, I forgot to reimplement the choice of format. I didn't notice this in part because the test suite doesn't currently cover the scripts (this will be fixed in the next iteration of `pyani`).

I've reimplemented and tested the download format choice in the latest commit: 43ba088

The following command-line now works for me, as I would expect:

```
genbank_get_genomes_by_taxon.py -t 203804 -v -l C_blochmannia_dl.log  -o issue_89_dl --email my.email@my.domain --format=gbk -f
```

Re: the `.fna` vs `.fna.gz` files. At the FTP source site all files are gzipped. They're downloaded as `.fna.gz` and then uncompressed on the local disk.

Please let me know if this fix works for you (if so, I'll close the issue), or if you have any further comments/questions.

Cheers,

L.

**Comment by jvollme** [comment]
Hi, sorry for the late reply. It seems to work nicely now. Thanks!
