### ISSUE TITLE
Error: This has possibly been a NUCmer run failure

### ISSUE THREAD

**Issue by krisdyZJU** [widdowquinn/pyani#93]
#### Summary:
As described, I installed pyani, but I met error when I execute
`./bin/average_nucleotide_identity.py -i tests/test_ani_data/ -o tests/test_ANIm_output -m ANIm -g`

#### Description:
the detail error message is like below:

> WANGdeMacBook-Pro:pyani-master WANG$ ./bin/average_nucleotide_identity.py -i tests/test_ani_data/ -o tests/test_ANIm_output -m ANIm -g
WARNING: At least one NUCmer comparison failed. ANIm may fail.
WARNING: Total alignment length reported in tests/test_ANIm_output/nucmer_output/NC_002696_vs_NC_010338.filter is zero!
WARNING: Total alignment length reported in tests/test_ANIm_output/nucmer_output/NC_002696_vs_NC_011916.filter is zero!
WARNING: Total alignment length reported in tests/test_ANIm_output/nucmer_output/NC_002696_vs_NC_014100.filter is zero!
WARNING: Total alignment length reported in tests/test_ANIm_output/nucmer_output/NC_010338_vs_NC_011916.filter is zero!
WARNING: Total alignment length reported in tests/test_ANIm_output/nucmer_output/NC_010338_vs_NC_014100.filter is zero!
WARNING: Total alignment length reported in tests/test_ANIm_output/nucmer_output/NC_011916_vs_NC_014100.filter is zero!
ERROR: This has possibly been a NUCmer run failure, please investigate
ERROR: NoneType: None

#### pyani Version:
0.2.4
#### Python Version:
Python 3.6.2
#### Operating System:
macOS 10.12.2 

Thanks for your reply in advance!

**Comment by krisdyZJU** [comment]
@widdowquinn could you please help to take a look? thanks.

**Comment by krisdyZJU** [comment]
no feedback?

**Comment by widdowquinn** [comment]
Hi Krisdy,

I haven't responded because I've been away from work, on holiday. I am, in fact, still on holiday. Also, you might want to consider that your requests have all been on weekends, and you should - in general (for many projects) - probably expect slower, or no, response on weekends.

The error being reported indicates that none of your test NUCmer runs have worked. Your first line of investigation should be to determine why that is. I am unable to reproduce your error on my machine.

The most common cause of this problem is that NUCmer is not configured correctly. Can you, for instance, run at the command-line one of the command-lines that the log file generates, e.g.

```
nucmer --mum -p tests/test_ANIm_output/nucmer_output/NC_002696_vs_NC_014100 tests/test_ani_data/NC_002696.fna tests/test_ani_data/NC_014100.fna; delta-filter -1 tests/test_ANIm_output/nucmer_output/NC_002696_vs_NC_014100.delta > tests/test_ANIm_output/nucmer_output/NC_002696_vs_NC_014100.filter
```

This may give more useful information about how and why the run is failing.

L.

**Comment by youlijun** [comment]
你好krisdyZJU，问题解决了吗？我也遇到同样的问题，谢谢你的回复

**Comment by widdowquinn** [comment]
Hi Youlijun,

If you have the same problem as krisdyZJU, then the issue for you will also be that the nucmer runs are not producing output. This is most likely because the tool is not configured in such a way that it can be seen and run by pyani.

Please check that you can run the nucmer command from the same environment that you run pyani, and that it gives reasonable output for a good set of input files that are expected to produces an alignment. Assuming that you are using pyani v0.2.x:

```bash
nucmer --mum -p tests/test_ANIm_output/nucmer_output/NC_002696_vs_NC_014100 \
tests/test_ani_data/NC_002696.fna tests/test_ani_data/NC_014100.fna; delta-filter -1 \
tests/test_ANIm_output/nucmer_output/NC_002696_vs_NC_014100.delta > \
tests/test_ANIm_output/nucmer_output/NC_002696_vs_NC_014100.filter
```

**Comment by NeeluBegum** [comment]
Dear @widdowquinn,

I have had the same error above, i did your suggested run for checking nucmer and i have received this error after performing the same as above:

2,3: RUNNING mummer AND CREATING CLUSTERS
# reading input file "/pyani-master/all_can/output_15jan3/nucmer_output/cdub_vs_calbi_1.ntref" of length 2975538
# construct suffix tree for sequence of length 2975538
# (maximum reference length is 536870908)
# (maximum query length is 4294967295)
# process 29755 characters per dot
#....................................................................................................
# CONSTRUCTIONTIME MUMmer3.23/mummer /pyani-master/all_can/output_15jan3/nucmer_output/cdub_vs_calbi_1.ntref 0.61
# reading input file "/pyani-master/all_can/test_in/calbi_1.fa" of length 2973464
# matching query-file "//pyani-master/all_can/test_in/calbi_1.fa"
# against subject-file "/pyani-master/all_can/output_15jan3/nucmer_output/cdub_vs_calbi_1.ntref"
# COMPLETETIME //MUMmer3.23/mummer //pyani-master/all_can/output_15jan3/nucmer_output/cdub_vs_calbi_1.ntref 0.71
# SPACE /MUMmer3.23/mummer /pyani-master/all_can/output_15jan3/nucmer_output/cdub_vs_calbi_1.ntref 7.01
4: FINISHING DATA
ERROR: Could not parse delta file,  
error no: 400


# details:
pyani v0.2.x:

**Comment by widdowquinn** [comment]
Hi Neelu,

Thank you for your interest in `pyani`.

This problem usually has one of two causes: `mummer` isn't installed correctly (but in your case I see that you have `nucmer` output, so that's not the problem), or the genomes being compared are too different to produce an alignment with `mummer`. I think that your problem might be the second one. 

Can you please check the contents of the file `cdub_vs_calbi_1.ntref` - I suspect that this may be empty.

L.

**Comment by NeeluBegum** [comment]
That file doesn't exist for me. I searched my entire computer and output file

**Comment by widdowquinn** [comment]
Hi Neelu,

What it looks like is that `nucmer` is trying to read for the `/pyani-master/all_can/output_15jan3/nucmer_output/cdub_vs_calbi_1.ntref` but cannot parse it. That could be because it is wrongly-formatted, empty, or does not exist. In this case it appears that the file does not exist.

If you can, please look at the detailed log output for `pyani` and identify the `nucmer` command that should generate or use this file, and try executing it at the command-line. If this does not work, the problem is most likely that your genomes are not similar enough to align together. If this is the case, you should be able to do the analysis by removing the very dissimilar genome from your input data set.

L.

**Comment by NeeluBegum** [comment]
Where can i access log output for pyani? Or what would be the file name?

**Comment by widdowquinn** [comment]
You can generate log output by specifying `-l <FILENAME>` or `--logfile <FILENAME>` when you run `pyani`. You should replace `<FILENAME>` with the path to the log file you want to write. For example, `--logfile mylogs.txt` would write the logs into a file called `mylogs.txt` in the directory you run `pyani` from.

This, and other options, are described in the documentation (v0.2.x - i.e. `average_nucleotide_identity.py`: [here](https://github.com/widdowquinn/pyani/blob/master/README_v_0_2_x.md); v0.3.x - i.e. `pyani`: [here](https://pyani.readthedocs.io/en/stable/))

**Comment by AlisaGU** [comment]
After add `--nucmer_exe $dirOfNucmer`, I fixed this problem.
