### ISSUE TITLE
TypeError when calling genbank_get_genomes_by_taxon.py

### ISSUE THREAD

**Issue by jvollme** [widdowquinn/pyani#97]
#### Summary:
When calling ```genbank_get_genomes_by_taxon.py``` with the ```--retries``` argument, I get a TypeError, because the argument is stored as a string, but evaluated as an integer.

I guess could be most easily fixed if all Integer arguments (```--retries```, ```--batchsize``` and ```--timeout```) would be explicitely set as "type = int" during the respective argparse ```parser.add_argument()``` calls.

**Comment by widdowquinn** [comment]
This issue should be fixed with commit 69503d39aae9e24f192a9ff6228315a3eb375059, and I've pushed a new version (v0.2.7) to PyPI and Docker so you should be able to get those with a `pip install` or `docker run`.

This should fix the issue, but please do raise another if you find any other problems.

L.
